version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    network_mode: host
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - node-red-data:/data
    restart: unless-stopped

volumes:
  node-red-data:
