{
 "title": "Mixing Overview - Unified",
 "tags": [ "mixing" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mixing 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-01.*/ or r[\"topic\"] =~ /.*plant\\/1.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Weight.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Volume.*/ or r[\"_field\"] =~ /.*Scale_Act.*/ or r[\"_field\"] =~ /.*MixTank_Temp.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Temperature.*/ or r[\"_field\"] =~ /.*Temp_Act.*/ or r[\"_field\"] =~ /.*Agitator_Act.*/ or r[\"_field\"] =~ /.*MixingTank_Agitator_Speed.*/ or r[\"_field\"] =~ /.*HighShear_Act.*/ or r[\"_field\"] =~ /.*HighShare_Speed.*/) |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mixing 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-02.*/ or r[\"topic\"] =~ /.*plant\\/2.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Weight.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Volume.*/ or r[\"_field\"] =~ /.*Scale_Act.*/ or r[\"_field\"] =~ /.*MixTank_Temp.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Temperature.*/ or r[\"_field\"] =~ /.*Temp_Act.*/ or r[\"_field\"] =~ /.*Agitator_Act.*/ or r[\"_field\"] =~ /.*MixingTank_Agitator_Speed.*/ or r[\"_field\"] =~ /.*HighShear_Act.*/ or r[\"_field\"] =~ /.*HighShare_Speed.*/) |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mixing 3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-03.*/ or r[\"topic\"] =~ /.*plant\\/3.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Weight.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Volume.*/ or r[\"_field\"] =~ /.*Scale_Act.*/ or r[\"_field\"] =~ /.*MixTank_Temp.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Temperature.*/ or r[\"_field\"] =~ /.*Temp_Act.*/ or r[\"_field\"] =~ /.*Agitator_Act.*/ or r[\"_field\"] =~ /.*MixingTank_Agitator_Speed.*/ or r[\"_field\"] =~ /.*HighShear_Act.*/ or r[\"_field\"] =~ /.*HighShare_Speed.*/) |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}