{
 "title": "Full Production Monitor",
 "tags": [
  "production",
  "monitor"
 ],
 "refresh": "5s",
 "panels": [
  { "title": "Mixing Line 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mix 1 Volume",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-01.*/ or r[\"topic\"] =~ /.*plant\\/1.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Weight.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Volume.*/ or r[\"_field\"] =~ /.*Scale_Act.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 1 Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-01.*/ or r[\"topic\"] =~ /.*plant\\/1.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Temp.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Temperature.*/ or r[\"_field\"] =~ /.*Temp_Act.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 1 Agitator Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-01.*/ or r[\"topic\"] =~ /.*plant\\/1.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*Agitator_Act.*/ or r[\"_field\"] =~ /.*MixingTank_Agitator_Speed.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 1 High Share",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-01.*/ or r[\"topic\"] =~ /.*plant\\/1.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*HighShear_Act.*/ or r[\"_field\"] =~ /.*HighShare_Speed.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 1 Trends",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-01.*/ or r[\"topic\"] =~ /.*plant\\/1.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Weight.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Volume.*/ or r[\"_field\"] =~ /.*Scale_Act.*/ or r[\"_field\"] =~ /.*MixTank_Temp.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Temperature.*/ or r[\"_field\"] =~ /.*Temp_Act.*/ or r[\"_field\"] =~ /.*Agitator_Act.*/ or r[\"_field\"] =~ /.*MixingTank_Agitator_Speed.*/ or r[\"_field\"] =~ /.*HighShear_Act.*/ or r[\"_field\"] =~ /.*HighShare_Speed.*/) |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Mixing Line 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Mix 2 Volume",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-02.*/ or r[\"topic\"] =~ /.*plant\\/2.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Weight.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Volume.*/ or r[\"_field\"] =~ /.*Scale_Act.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 2 Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-02.*/ or r[\"topic\"] =~ /.*plant\\/2.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Temp.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Temperature.*/ or r[\"_field\"] =~ /.*Temp_Act.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 2 Agitator Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-02.*/ or r[\"topic\"] =~ /.*plant\\/2.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*Agitator_Act.*/ or r[\"_field\"] =~ /.*MixingTank_Agitator_Speed.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 2 High Share",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-02.*/ or r[\"topic\"] =~ /.*plant\\/2.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*HighShear_Act.*/ or r[\"_field\"] =~ /.*HighShare_Speed.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 2 Trends",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-02.*/ or r[\"topic\"] =~ /.*plant\\/2.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Weight.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Volume.*/ or r[\"_field\"] =~ /.*Scale_Act.*/ or r[\"_field\"] =~ /.*MixTank_Temp.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Temperature.*/ or r[\"_field\"] =~ /.*Temp_Act.*/ or r[\"_field\"] =~ /.*Agitator_Act.*/ or r[\"_field\"] =~ /.*MixingTank_Agitator_Speed.*/ or r[\"_field\"] =~ /.*HighShear_Act.*/ or r[\"_field\"] =~ /.*HighShare_Speed.*/) |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Mixing Line 3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Mix 3 Volume",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-03.*/ or r[\"topic\"] =~ /.*plant\\/3.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Weight.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Volume.*/ or r[\"_field\"] =~ /.*Scale_Act.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 3 Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-03.*/ or r[\"topic\"] =~ /.*plant\\/3.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Temp.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Temperature.*/ or r[\"_field\"] =~ /.*Temp_Act.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 3 Agitator Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-03.*/ or r[\"topic\"] =~ /.*plant\\/3.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*Agitator_Act.*/ or r[\"_field\"] =~ /.*MixingTank_Agitator_Speed.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 3 High Share",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-03.*/ or r[\"topic\"] =~ /.*plant\\/3.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*HighShear_Act.*/ or r[\"_field\"] =~ /.*HighShare_Speed.*/) |> last()"
    }
   ]
  },
  {
   "title": "Mix 3 Trends",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"SPP\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"topic\"] =~ /.*MIX-03.*/ or r[\"topic\"] =~ /.*plant\\/3.*/) |> filter(fn: (r) => r[\"_field\"] =~ /.*MixTank_Weight.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Volume.*/ or r[\"_field\"] =~ /.*Scale_Act.*/ or r[\"_field\"] =~ /.*MixTank_Temp.*/ or r[\"_field\"] =~ /.*Mixing_Tank_Temperature.*/ or r[\"_field\"] =~ /.*Temp_Act.*/ or r[\"_field\"] =~ /.*Agitator_Act.*/ or r[\"_field\"] =~ /.*MixingTank_Agitator_Speed.*/ or r[\"_field\"] =~ /.*HighShear_Act.*/ or r[\"_field\"] =~ /.*HighShare_Speed.*/) |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}