[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "secret-token-mitrphol-history"
  organization = "mitrPholMixing"
  bucket = "MixingData"
  # Exclude plant data from general historical bucket if desired, or keep both.
  # For now, let's keep all in MixingData for backward compatibility.

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "secret-token-mitrphol-history"
  organization = "mitrPholMixing"
  bucket = "SPP"
  [outputs.influxdb_v2.tagpass]
    topic = [
      "mixing/plant/1", "mixing/plant/1/#",
      "mixing/plant/2", "mixing/plant/2/#",
      "mixing/plant/3", "mixing/plant/3/#",
      "MIX/plant/1", "MIX/plant/2", "MIX/plant/3",
      "/MIX-01", "/MIX-02", "/MIX-03",
      "MIX-01", "MIX-02", "MIX-03",
      "SPP/#"
    ]

[[inputs.mqtt_consumer]]
  servers = ["tcp://host.docker.internal:1883"]
  topics = [
    "#"
  ]
  username = "xMixingNode-1"
  password = "x123456"
  data_format = "json"
  topic_tag = "topic"

[[inputs.ping]]
  urls = ["192.168.121.11", "google.com"]
  count = 1
  ping_interval = 1.0
  timeout = 10.0
  interval = "30s"
