[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "secret-token-mitrphol-history"
  organization = "mitrPholMixing"
  bucket = "MixingData"

[[inputs.mqtt_consumer]]
  servers = ["tcp://host.docker.internal:1883"]
  topics = [
    "#"
  ]
  username = "xMixingNode-1"
  password = "x123456"
  data_format = "json"
  topic_tag = "topic"
